---
kind: pipeline
type: docker
name: development

trigger:
    branches:
        - master

steps:
    - name: publish
      image: plugins/docker
      settings:
        repo: hachikoapp/goapp
        tags: [ "${DRONE_COMMIT_SHA}", "latest"]
        username:
            from_secret: docker_username
        password:
            from_secret: docker_password